#!/usr/bin/with-contenv bash

get_iyuu() {
    if [[ ! -d /iyuu/.git ]]; then
        git clone https://gitee.com/ledc/IYUUAutoReseed.git /iyuu
    else
        git -C /iyuu pull
    fi

    if [[ ! -s /iyuu/config/config.php ]]; then
        cp /iyuu/config/config.sample.php /iyuu/config/config.php
    fi
}

get_iyuu 2>&1 | sed "s#^#[cont-init.d] $(basename $0): \1#g"