#!/usr/bin/with-contenv bash

make_link() {
    if [[ ! -s /userdata/config.sample.php ]] || [[ $(diff /iyuu/config/config.sample.php /userdata/config.sample.php 2>/dev/null) ]]; then
        cp -fv /iyuu/config/config.sample.php /userdata/config.sample.php
    fi

    if [[ ! -s /userdata/config.php ]]; then
        cp -fv /iyuu/config/config.sample.php /userdata/config.php
    fi

    if [[ ! -f /iyuu/config/config.php ]] || [[ $(readlink -f /iyuu/config/config.php) != /userdata/config.php ]]; then
        rm -rf /iyuu/config/config.php 2>/dev/null
        ln -sf /userdata/config.php /iyuu/config/config.php
    fi
}

make_link 2>&1 | sed "s#^#[cont-init.d] $(basename $0): \1#g"