#!/usr/bin/with-contenv bash

set_cron() {
    if [[ -z ${CRON_GIT_PULL} ]]; then
        CRON_GIT_PULL="23 6,19 * * *"
    fi

    if [[ -z ${CRON_IYUU} ]]; then
        CRON_IYUU="51 7,19 * * *"
    fi

    echo "设置cron..."
    echo -e "${CRON_GIT_PULL} git -C /iyuu pull\n${CRON_IYUU} php /iyuu/iyuu.php" | crontab -

    echo "当前crontab如下："
    crontab -l
}

set_cron 2>&1 | sed "s#^#[cont-init.d] $(basename $0): \1#g"